spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 25
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
  liquibase:
    change-log: db/changelog/db.changelog-master.xml

management:
  endpoints:
    web:
      exposure:
        include: [health,actuator]

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}

app:
  access-ttl: ${ACCESS_TTL} # sec
  refresh-ttl: ${REFRESH_TTL} # sec
  keys:
    public-path: classpath:keys/public.key
    private-path: classpath:keys/private.key
  jwt:
    issuer: mapping-service